/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Declaration of a limited coverage of a tile matrix.
 */
export interface TileMatrixLimits {
  /**
   * Minimum tile row index.
   */
  minTileRow: number;
  /**
   * Maximum tile row index.
   */
  maxTileRow: number;
  /**
   * Minimum tile column index.
   */
  minTileCol?: number;
  /**
   * Maximum tile column index.
   */
  maxTileCol?: number;
}
