/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Based on the MBTiles spec. File format of the tile data. *.pbf as a format refers to gzip-compressed vector tile data in Mapbox Vector Tile format.
 */
export type TileFormat = "pbf" | "jpg" | "png" | "webp";
